version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yt-quiz-gen
    volumes:
      - ./:/app
    working_dir: /app
    command: python main.py
    ports:
      - "7860:7860" # Exposing port 7860 which is default for Gradio
    environment:
      - PYTHONUNBUFFERED=1
