import re
import json

JUDGE_PROMPT = """
You will be given a descriptive text about a topic of a YouTube video,
a multiple choice question generated by an LLM from the topic, the
four options to choose the answer, and the correct answer.

Your task is to provide a 'difficulty rating' of the question. The
difficulty levels are 'Easy', 'Medium', 'Hard', and 'Expert'. Critically
analyze the question, choices and correct answer based on the following
criteria:

- sentence complexity of the question
- vocabulary difficulty
- concepts involved to answer the question

Provide your feedback as a JSON object as follows:
{
    "rating": (your rating, easy/medium/hard/expert)
    "feedback": (your feedback)
}

Now, here are the topic, question, choices, and answer:

Topic: {topic}
Question: {question}
Choices: {choices}
Answer: {answer}

Rating:
Feedback:
"""


def evaluate_question(llm, **kwargs):
    prompt = JUDGE_PROMPT.format(**kwargs)
    response = llm.complete(prompt)

    feedback = kwargs.pop("return_feedback", None)

    try:
        response_text = re.sub(r"(```|json)", "", response.text)
        json_response = json.loads(response_text)
    except Exception as e:
        raise e

    if feedback:
        return json_response["rating"], json_response["feedback"]

    return json_response["rating"]
